# Generated by Django 4.2.20 on 2025-03-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='hobby',
            field=models.CharField(default='', max_length=255),
        ),
    ]
